### PR TITLE
Vertically center button text.

### PR DESCRIPTION
**Pull request by rchinerman**
This will vertically-align the text within the Button component.

### CODE REVIEW

**Comment by brunolemos** [comment]
It's already being centered with `alignItems: 'center', justifyContent: 'center'`, is there any layout broken? Please send screenshots. Also it doesn't seem `lineHeight` is a valid style property for Views, only for Texts.

**Comment by rchinerman** [comment]
The text box is centered, but the text within the text box is a tiny bit off.

Image 1
Image 1

You can see it particularly clearly with the 'S' in the second image.

**Comment by rchinerman** [comment]
@brunolemos That's what I get for programming late at night and not checking console. It worked when I tried it (but with the warning) because the line-height was inherited by Text, but yeah that should have been on the Text.

**Comment by brunolemos** [comment]
Made lots of related fixes on #66. This a bit more complicated because of differences between mobile and web. Sometimes it fixed the alignment on web and broke on mobile. Instead of `lineHeight: buttonSize` I used `lineHeight: fontSize` and other changes as well.

**Pull request closed without merging**
