### PR TITLE
Change color of tray icon when there are unread notifications

### PR DESCRIPTION
**Pull request by dkniffin**
No unread notifications:
Screen Shot 2019-06-30 at 9 34 51 PM

At least one unread notification:
Screen Shot 2019-06-30 at 9 35 17 PM

Related to #90

### CODE REVIEW

**Comment by dkniffin** [comment]
I haven't tested this on anything except mac. Not sure if that matters for merging this or not.

**Comment by brunolemos** [comment]
This is great @dkniffin, thanks!

**Comment by brunolemos** [comment]
I pushed a commit to remove the hook from the reduce, because that breaks one of the hooks rules and causes this error: 

image

**Comment by dkniffin** [comment]
@brunolemos Mind pushing another release soon? I'd like to start using this without having to run the app locally

**Comment by brunolemos** [comment]
@dkniffin I’m trying to get one more thing together in the same release, but you can run `yarn workspace @devhub/desktop build` that it will create a production app exactly the same as the one I’d release.

**Pull request merged**
