### PR TITLE
Added font smoothing for improved legibility on web

### PR DESCRIPTION
**Pull request by edxds**
This helps improve the appearance of bolder text on the web. It also makes font icons sharper

### CODE REVIEW

**Comment by brunolemos** [comment]
Hi! Which browser and operational system did you see a difference? I don't see any

**Comment by edxds** [comment]
Well, I just now noticed that it only affects macOS. It still makes a difference though, here's a comparison of Chrome 71 on macOS 10.13.6

Without smoothing
without

With smoothing
with

Without smoothing
without1

With smoothing
with1

**Comment by brunolemos** [comment]
I could not reproduce this at all (maybe because my mac is retina?), but I'll accept. Thanks!

**Comment by edxds** [comment]
Yeah, probably. I'm running on 1080p. Safari and Firefox handle font rendering better by default.

**Pull request merged**
