### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by mtsmfm**

### CODE REVIEW

**Comment by brunolemos** [comment]
This pull request **fixes 1 alert** when merging 34bc9fb4dd7920476f64c8018db6daeb05e2d59c into 6aa24bb96658ce2541f69f9eccfc3d65826c726b - [view on LGTM.com](https://lgtm.com/projects/g/devhubapp/devhub/rev/pr-474d81c98cfd293acd94cd4041973e45dab6dedf)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by brunolemos** [comment]
Thanks for taking the time!

Don't worry about this, there's a command to fix these things:

`yarn lint --fix && yarn format`

**Comment by mtsmfm** [comment]
> Don't worry about this, there's a command to fix these things:

Do you have any plan to apply this fix to the entire codebase?
My editor always suggests removing them so it's noisy when I develop devhub 😓

**Comment by brunolemos** [comment]
Done.

**Pull request merged**
