### PR TITLE
Desktop

### PR DESCRIPTION
**Pull request by amorist**
## TODO:

- [x] app logo

- [x] menubar app 

- [x] TouchBar

- [x] build

Do you have any advices?

## dev
```
yarn
yarn dev:desktop
```

## build
```
yarn build:desktop
```

image

### CODE REVIEW

**Comment by amorist** [comment]
#2

**Comment by amorist** [comment]
default is menubar app

**Comment by brunolemos** [comment]
Thanks for your work @amorist, really appreciate it!

Here's a few thoughts:

### Code sharing

I see lot's of code was copied from the `web` project, maybe we could avoid duplication? Since it's a monorepo, one package can use code from the other. Or maybe we could use a npm script with a `cp` command, so we don't have to always manually duplicate changes between web and electron.

### Auto update

Can we setup the electron auto update so people always have the latest version?

### Top arrow and settings style

See this example of arrow (the settings I'm still not sure if we should do like this):

image


### Quick switch between menubar and desktop mode

I like how the app Harvest allows this:

kapture 2018-12-18 at 15 33 07


### Native apps instead of Electron

We can use Electron for now, but for the future I'd love to use [react-native-macos](https://github.com/ptmt/react-native-macos) and [react-native-windows](https://github.com/Microsoft/react-native-windows). I don't know if they will work, but I'll definitely play with them later.

**Comment by brunolemos** [comment]
### External links

The links are being opened inside electron, but they should open in the users' default browser. Specially the authentication one, so the user can see the URL and trust it.

**Comment by amorist** [comment]
> When scrolling horizontally (on a small window) it should jump to the next column. It does this on chrome mobile, not sure why not happening on electron

https://caniuse.com/#feat=css-snappoints

image

electron process.versions.chrome `66.0.3359.181`

**Comment by brunolemos** [comment]
> electron process.versions.chrome 66.0.3359.181

Have you tried Carlo? Google recently launched an Electron alternative, instead of bundling with chrome it uses the Chrome from the user machine: https://github.com/GoogleChromeLabs/carlo

**Comment by amorist** [comment]
i will try
```
if (CSS.supports('scroll-snap-type: x mandatory')) {
  // use css scroll snap
} else {
  // other
}
```

**Comment by brunolemos** [comment]
> i will try if (CSS.supports('scroll-snap-type: x mandatory')) {

Don't worry about this, electron should update chrome soon right?

**Comment by amorist** [comment]
> > i will try if (CSS.supports('scroll-snap-type: x mandatory')) {
> 
> Don't worry about this, electron will eventually upgrade chrome
Yes electron 4.0.0-beta chrome version is 69.0.3497.106

**Comment by brunolemos** [comment]
We can use electron beta if it's not too buggy

**Comment by amorist** [comment]
> We can use electron beta if it's not too buggy

OK!

**Comment by amorist** [comment]
Update:

- [ ] Code sharing **WIP**

- [ ] Auto update **WIP**

- [ ] Top arrow and settings style **WIP**

- [ ] Quick switch between menubar and desktop mode **WIP**

- [ ] External links: The authentication link is being opened inside electron, but it should open in the users' default browser, so the user can see the URL and trust it.  **WIP**

- [x] When scrolling horizontally (on a small window) it should jump to the next column. It does this on chrome mobile, not sure why not happening on electron **upgrade electron version 4.0.0-beta.11**

- [x] App shows the default electron logo at the dock **unpackaged app default logo**

- [ ] CSS bug when column event filters are opened (scroll not working and visible overflow content)
A few other enhancements **WIP**

- [ ] Use circle icon instead of square **WIP**

- [x] Set min width to constants.MIN_COLUMN_WIDTH

**Comment by brunolemos** [comment]
> CSS bug when column event filters are opened (scroll not working and visible overflow content)

Fix is on master

> Use circle icon instead of square

PNG assets are on master (https://github.com/devhubapp/devhub/tree/master/packages/mobile/assets)

**Comment by brunolemos** [comment]
> Quick switch between menubar and desktop mode
> Top arrow and settings style

Looking nice! 🤩

**Comment by brunolemos** [comment]
> Code sharing 

Don't worry about this now, we can improve this in the future

> External links: The authentication link is being opened inside electron
> Auto update

Just these left I think right? 🎉
I don't know much about the auto update, do I have to create some account somewhere?

**Comment by amorist** [comment]
Code signing is required on macOS

**Comment by amorist** [comment]
> External links: The authentication link is being opened inside electron
I don't know how auth when authentication link opened by user default browser

**Comment by brunolemos** [comment]
I plan to work on this this weekend.

**Comment by brunolemos** [comment]
Thanks for your work @amorist, really appreciate it! 🎉🎉

I've opened #69 and will continue work there.

I'd love if you could keep helping with the desktop apps!
Hopefully we can launch them soon.

**Pull request merged**
