### PR TITLE
Sidebar: Draggable Items

### PR DESCRIPTION
**Pull request by renatoagds**
This is a 50% of https://github.com/devhubapp/devhub/issues/42

Now you can drag and drop items in sidebar to organize the columns.

devhub-4

### CODE REVIEW

**Comment by renatoagds** [comment]
@brunolemos please, take a look.

**Comment by brunolemos** [comment]
Thanks for the pull request, the gif looks great!

Did you check if it works on both android and ios native?

I see there's dom access and a css class so I'm assuming you made it for web. One tip is to make it for mobile, and then it usually work on web automatically.

**Comment by renatoagds** [comment]
@brunolemos For mobile it stays the same as today. Do you prefer an refactor to working in all envs? I'm saying refactor, because SortableJS is made only for web and I don't remember a library that could be use for both, do you know? Otherwise we'll need to do all the drag and drop handle by ourselves. If you prefer for both envs, I could work on it, but will take a few more days, since I'll return for my job tomorrow haha

**Comment by brunolemos** [comment]
Yeah, we better do it cross platform from the start, otherwise one platform will slowly start to lag behind the other. 

Pretty sure that are some code or lib out there that we can use, but I haven't tried them yet. 

One possible one: https://github.com/computerjazz/react-native-draggable-flatlist

**Comment by renatoagds** [comment]
@brunolemos Makes sense! I'll take a look into this one that you shared and provided an update into this PR. 🤘

**Comment by brunolemos** [comment]
@renatoagds let me know if you plan to change the lib, otherwise I'll take a look

**Comment by renatoagds** [comment]
@brunolemos I'll take a look this weekend. Sorry for the delay. Is difficulty for me doing OSS on the week

**Comment by renatoagds** [comment]
@brunolemos I tried to implement this with: https://github.com/computerjazz/react-native-draggable-flatlist

But it didn't work as expected. Tomorrow I'll try to implement this in top of: https://github.com/deanmcpherson/react-native-sortable-listview

**Comment by renatoagds** [comment]
@brunolemos I made a update and worked with https://github.com/computerjazz/react-native-draggable-flatlist

I'm justing finishing a problem with mobile version. If you want, make a try of my branch. :+1:

**Comment by brunolemos** [comment]
Nice! I tried your branch, the dragging worked on web, needs to set `onMoveEnd` to save the new positions. What's the issue on mobile?

I found it weird that it didn't have any animation, there is in the readme.

**Comment by brunolemos** [comment]
I'm still considering other implementations besides these I sent as an example.

On #87 I'll probably add `react-springs`, and I've seem some great drag&drop using `react-springs` + `hooks`, for example: https://codesandbox.io/embed/r5qmj8m6lq.

I should play with them soon. Needs to confirm it works on react-native.

But anyway, I can merge this and make the changes later.

**Comment by brunolemos** [comment]
On #87 I'll probably add `react-spring`, and I've seem some great drag&drop using `react-spring` + `hooks`, for example: https://codesandbox.io/embed/r5qmj8m6lq.

I should play with them soon.

**Comment by brunolemos** [comment]
TweetDeck UX for comparison, we should try to match it:

- Smooth animation
- The icons have a background
- Tooltips (#8)
- There's no delay before the drag starts
- The position change only happens when the icon being dragged crosses the middle of the other one
- Columns reorder as well

kapture 2019-01-09 at 17 51 34

**Comment by renatoagds** [comment]
@brunolemos Yes! I share the same feeling about the animations. Based on your feedback and the sandbox that you sent. I would like to propose add `react-spring` and move out of libraries. Looking the current draggable libraries for RN, they are primitive and looks like we wouldn't achieve our goal using them.

**Comment by renatoagds** [comment]
@brunolemos hey, sorry for the delay, I changed my job and things got crazy. I'm closing this one because I want to work in a recap of this feature following TweetDeck experience. I'll return with a new PR focused on that.

**Pull request closed without merging**
