### PR TITLE
Add `rimraf` to use instead `rm -rf`

### LINKED ISSUE #74: "yarn dev" fails on Windows
# 😓 Issue

Running `yarn dev` fails due to missing `rm` on Windows.

image

The problem were due to following changes
1. https://github.com/devhubapp/devhub/pull/47/files#diff-86e76d873d64676026fa1247d70fa4a7R8
1. https://github.com/devhubapp/devhub/pull/47/files#diff-86e76d873d64676026fa1247d70fa4a7R12

# 🙏 Suggestion

Would it be possible to add a dev dependency to remove the `dist` folder instead of using OS specific `rm` command?

### PR DESCRIPTION
**Pull request by gregoryfm**
Fix #74 

Replace `rm -rf` with the `rimraf` package to fix issue on Windows.

### CODE REVIEW

**Comment by brunolemos** [comment]
Thanks! The app uses other command, like `pushd`, do they work on windows?
If not, maybe we should use this one: https://github.com/shelljs/shx

**Comment by gregoryfm** [comment]
Unfortunately I don't have a windows machine to test.
But I searched into the `pushd` issues and found this: rs/pushd/issues/97 (Is it this package, right?)

**Comment by brunolemos** [comment]
I decided not to install third party packages to be able to run a `rm -rf` command. I think Windows users should use Bash instead. Details here: https://github.com/devhubapp/devhub/issues/74#issuecomment-450276099

Thanks for the PR!

**Comment by brunolemos** [comment]
Nevermind, merged because I noticed other repositories use this `rimraf` as well, like [Spectrum](https://github.com/withspectrum/spectrum/blob/7d5a8514deb3878652e789464b064d91a796d894/package.json#L229).

Thanks!

**Pull request merged**
