### PR TITLE
Finish Desktop apps

### LINKED ISSUE #2: Desktop client
https://electronjs.org/

### PR DESCRIPTION
**Pull request by brunolemos**
Closes #2

Pending tasks before launching the desktop apps. Contributions welcome!

- [x] Merge #47 (thanks @amorist!)
- [x] Fix `package.json` versions (#72, https://github.com/devhubapp/devhub/commit/f8a79db2a2ce2281afd75aa7f0d6951da186895a)
- [x] Reuse the code from web, so we avoid code duplication, get CRA's features like auto reload etc
- [x] Auto reload Electron on change
- [x] Make login work on user default browser, so the user can see the url and trust it
- [x] Implement deep linking
- [x] Change default menubar window size
- [x] Change default desktop window size
- [x] Change app dock icon
- [x] Change app tray icon
- [x] [macOS] Make tray icon adapt for dark and light macOS themes
- [x] When app is on menubar mode, hide icon from dock (by @amorist)
- [x] ~Fix arrow not showing~
- [x] ~Change arrow color based on current theme~
- [x] ~Change how the arrow was implemented, do it like Harvest, it seems to do it outside of the main BrowserWindow~
- [x] ~Fix bottom bar label being cut (removing the arrow will fix this)~
- [x] Remove arrow
- [x] Always horizontal align menubar app in the middle
- [x] Fix lag after menubar -> desktop mode transition
- [x] Rethink how this menubar-mode/desktop-mode should work (e.g. currently one can be logged in and the other one logged out, and other bugs caused by multiple BrowserWindow)
- [x] Change how to switch between desktop/menubar modes; use a menu/tray option instead of the drag-to-specific-position way
- [x] Make Desktop mode the default one
- [x] Make Desktop mode be frameless like the menubar
- [x] Create only one window, reuse between Desktop and Menubar
- [x] Fix Menu and, by consequence, fix Copy, Paste, Select All, etc
- [x] Remove empty button from TouchBar
- [x] Option to make window be always at the center
- [x] Handle Full Screen Mode
- [x] Allow showing DevTools on development only
- [x] Show options on Dock icon, Menu and Tray icon
- [x] Add menu items to open DevHub on GitHub, Report bug and Send feedback
- [x] Fix app not reopening after Cmd+W
- [x] Run sync every time the window is opened/focused (e.g. when changing between apps, make sure the BrowserWindow visibility state goes to hidden; or manually trigger the redux SYNC_DOWN action)
- [x] Remember last window dimension/position and restore it (and also the "Lock on center" option)
- [x] Setup publishing binaries to github releases
- [x] Setup code signing
- [x] Setup auto updater
- [ ] Sync Saved items between devices (#70)
- [x] [Windows] Fix app.dock crash
- [x] [Windows] Hide icon from taskbar on menubar mode
- [x] [Windows] Show window frames
- [x] [Windows] Fix menubar mode
- [x] [Windows] Handle all taskbar positions for menubar mode
- [x] [Windows] Disable lockOnCenter by default
- [x] [Windows] Fix devhub:// protocol on dev mode
- [x] [Windows] Fix oauth (devhub:// is opening a new browserwindow and not logging in)
- [ ] [Windows] Change TitleBar color based on current theme
- [x] Disable nodeIntegration as a security precaution
- [x] [BUG] App is getting super buggy after login on a production build. The logo image disappears and if you press Reload it will stay stuck on an empty window
- [x] Test on macOS
- [x] Test on windows
- [x] Test on linux _(super buggy)_
- [ ] Fix buggy linux

### CODE REVIEW

**Comment by amorist** [comment]
> Setup auto updater

https://github.com/electron/update-electron-app

## Requirements

Before using this module, make sure your Electron app meets these criteria:

- Your app runs on macOS or Windows
- Your app has a public GitHub repository
- Your builds are published to GitHub Releases
- Your builds are [code signed](https://github.com/electron/electron/blob/master/docs/tutorial/code-signing.md)

**Comment by amorist** [comment]
> When app is on menubar mode, hide icon from dock

#71

**Comment by brunolemos** [comment]
@amorist I had to make lot's of changes because having two BrowserWindow was problematic. Also made some fixes, removed the arrow and made the desktop mode the default one.

**Comment by brunolemos** [comment]
Almost ready. #70 is the only one that should require more work.

**Comment by amorist** [comment]
can't start electron use `dev:desktop`

image

**Comment by brunolemos** [comment]
@amorist why not, any error message? Make sure you have the latest code and run `yarn` before because it has a new dependency.

**Comment by brunolemos** [comment]
@amorist I can't reproduce. Try opening it manually: `yarn workspace @devhub/desktop start`

**Comment by brunolemos** [comment]
Maybe it's because of the `wait-on` dependency.

**Comment by brunolemos** [comment]
@amorist try upgrading your nodejs to the latest version (10+)

**Comment by amorist** [comment]
@brunolemos 
Fixed this issue by restarting the computer :smile:

**Comment by brunolemos** [comment]
No idea what's causing this:

> - [ ] App is getting super buggy after login. The logo image disappears and if you press Reload it will stay stuck on an empty window

I think it has something to do with the `devhub://` protocol, I don't know. After the login this happens.

**Comment by brunolemos** [comment]
> [BUG] App is getting super buggy after login on a production build. The logo image disappears and if you press Reload it will stay stuck on an empty window

Fixed by https://github.com/devhubapp/devhub/pull/69/commits/3896e8d819d1c83112a7f88b1c6509d6163177fa and https://github.com/devhubapp/devhub/pull/69/commits/aa9dd1239f324f3e61e3690d9515857d4eb62e7d.

**Comment by brunolemos** [comment]
https://github.com/devhubapp/devhub/issues/2#issuecomment-450548000

**Pull request merged**
